### ISSUE TITLE
What happens if server crashes before running the job?

### ISSUE THREAD

**Issue by theodorDiaconu** [msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks#28]

**Comment by msavin** [comment]
Each server monitors if there is a dominant server running the jobs. It checks when that server was last active. If it was not active for say, 5 minutes, the first server to spot it will take over.

See: 
https://github.com/msavin/SteveJobs/tree/master/package/server/imports/operator/dominator

**Comment by totalvm** [comment]
What if all servers crash?
Or have to be restarted for some reason?

Will the job be saved somewhere where they can be restarted?

**Comment by msavin** [comment]
Unfortunately, Steve Jobs cannot defy the laws of physics. If all the servers crash, then it cannot run until a new one is started. All the jobs and their state are stored in MongoDB. For maximum reliability, I would suggest using a non-replicated setup with  write concerns set to the highest level.
