### ISSUE TITLE
"failed" or "failure" ?

### ISSUE THREAD

**Issue by gary-menzel** [msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks#35]
Hi Max,

I've been giving V3 a workout over the weekend (I had a horrid day on Friday with hosting issues that also triggered massive amounts of problems with jobs and multi-instance restarts after network failures - so decided to cut everything over and improve the error trapping and processing).....

However, in a number of places in the code you call `getJob` with the following....
```
   allow: ["pending", "failed"],
   message: '<appropriate message if it does not find a job>'
```
And it seems to me as though "failed" should be "failure" (or the `state` written to the DB should be `failed` instead of `failure`) as some of the routines are not behaving as expected and "failed/failure" jobs will not be found... specifically the `cancel` function (but I can see it on others as well).

I've basically cut everything over and am committed to using this now - so it is about to become a PRODUCTION issue.  I can just go into the DB and delete these failed jobs but I would like my in-app jobs console to work correctly using the API.

**Comment by msavin** [comment]
Good catch - thank you for reporting this. I just pushed 3.0.1 with a fix for this.

Once you deploy the new version, it will retry all the failed jobs, and then continue running pending jobs.

**Comment by gary-menzel** [comment]
Thanks Max - I've installed the update and will leave that running on my local machine for the rest of the day (7:30am or so here in Australia) while I go to my "day" job.  I've got a bunch of log statements and the "flakey" service usually times out within 12 hours so.

I'd rather let it fail normally than force it (but will do if the problem hasn't happened by then).

I'll let you know.

**Comment by msavin** [comment]
It sounds like this has been resolved. If it continues, please let me know.
