### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by DirkStevens** [msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks#39]
Hi Max,

Since working with the Jobs package I've been getting

`(node:8326) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
`

Have you seen this before?  Any thoughts what may trigger this in my scheduled methods?

Cheers,

Dirk

**Comment by msavin** [comment]
First time hearing/seeing this. I wonder if its something in the code of the jobs you are creating.

**Comment by DirkStevens** [comment]
It probably is :-/
